// -------------------   Routes with auth folder  -------------------------------------------------------------
// if folders as -->> auth/login/page.tsx
// auth  -->> Needed 'auth' in the routes as localhost:3000/auth/register 

// if folders as -->> (auth)/login/page.tsx
// (auth)  -->> Won't needed the routes as localhost:3000/auth/register can directly use localhost:3000/register
// ________________________________________________________________________________________________________________


// layout.tsx  -->> Renders the actual content -> {children}
// ________________________________________________________________________________________________________________

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Clerk NextJS for Authentication Dashboard
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import './globals.css'
// shadcn for Body themes of light and dark
import { ThemeProvider } from "@/components/theme-provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{baseTheme: dark}}>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
              attribute="class"
              forcedTheme="dark"
              storageKey="RealStream-theme"
              disableTransitionOnChange
            >
            {/* <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn> */}
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
